# Project information
site_name: Transformers-HuggingFace-PyTorch

# define TOC or order of website-
nav:
  - Introduction: index.md
  - Pipeline: 1tranformer-pipeline.md
  - UsingTransformer: 
    - 2UsingTransformerIntro.md
    - Behind The Pipeline: 2_1BehindPipeline.md
    - Models: 2_2Models.md
    - Tokenizers: 2_3Tokenizers.md
    - Handling Multiple Sequences: 2_4HandlingMultipleSequences.md
    - Putting All Together: 2_5PuttingAllTogether.md
  - FineTuningPretrainedModel: 
    - 3FineTuningPretrainedModel.md
    - Processing Data: 3_1ProcessingData.md
    - Fine-Tuning A Model with Trainer API: 3_2ModelFineTuningWithTrainerAPI.md
    - Full Training: 3_3FullTraining.md
  - SharingModelsAndTokenizers:
    - 4HuggingFaceHub.md
    - Using Pretrained Models: 4_1UsingPretrainedModels.md
    - Sharing Pretrained Models: 4_2SharingPretrainedModels.md
    - Building a Model Card: 4_3BuildingModelCard.md
  - HuggingFaceDatasetsLibrary:
    - 5HuggingFaceDatasetsLibrary.md
    - Loading Custom Datasets: 5_1LoadCustomDataset.md
    - Slice And Dice a Dataset: 5_2SliceDiceDataset.md
    - Big Data with Datasets: 5_3BigData.md
    - Creating Your Own Dataset: 5_4CreatingOwnDataset.md
    - Semantic search with FAISS: 5_5SemanticSearchWithFAISS.md
  - HuggingFaceTokenizersLibrary:
    - 6HuggingFaceTokenizersLibrary.md
    - Training a new tokenizer from an old one: 6_1TrainingNewTokenizerFromOld1.md
    - Fast tokenizers special powers: 6_2FastTokenizersSpecialPowers.md
    - Fast tokenizers in QA pipeline: 6_3FastTokenizersInQApipeline.md
    - Normalization and pre-tokenization: 6_4NormalizationPreTokenization.md
    - Byte-Pair Encoding tokenization: 6_5BytePairEncodingTokenization.md
    - WordPiece tokenization: 6_6WordPieceTokenization.md
    - Unigram tokenization: 6_7UnigramTokenization.md
    - Building a tokenizer, block by block: 6_8BuildingATokenizer.md
  - MainNLPTasks:
    - 7MainNLPTasks.md


site_author: Pallavi Saxena
site_description: >-
  DESCRIPTION

# Repository
repo_name: pallavi176/Transformers-HuggingFace-PyTorch
repo_url: https://github.com/pallavi176/Transformers-HuggingFace-PyTorch

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes 
    - toc.integrate
    - navigation.top
    - content.tooltips
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime    
  # logo: PyTorch_logo_icon.svg
  
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/pallavi176
    - icon: fontawesome/brands/twitter
      link: https://github.dev/pallavi176
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/pallavi-saxena-as/
    - icon: fontawesome/brands/instagram
      link: https://github.dev/pallavi176

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js #?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  
plugins:
  - search

copyright: |
  &copy; 2022 <a href="https://github.dev/pallavi176"  target="_blank" rel="noopener">Pallavi Saxena</a>